buildConfig: ./behavior-config.yml
behavior: ./behaviors/gofundme/campaign.js
url: 'https://www.gofundme.com/f/23bwcr8'

# path to chrome executable or command
chromeEXE: /usr/local/bin/chromium
openDevTools: true

mode: build-watch
# available options:
#  - build-watch: build and run the behavior watching for changes
#  - build: build and run the behavior once
#  - built: just run the previously built behavior

# time values in seconds
#timeout: 60
#slowmo: 10
